apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: sam
spec:
  selector:
    matchLabels:
      app: sam
      tier: frontend
  template:
    metadata:
      labels:
        app: sam
        tier: frontend
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql-svc
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: WORDPRESS_DB_USER
          value: sj
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim